services:
  atlchat:
    init: true
    container_name: atlchat
    build: .
    ports:
      - "6697:6697/tcp"
    volumes:
      - data:/ircd
      - ./ircd.yaml:/ircd/ircd.yaml:ro
      - ./ergo.motd:/ircd/ergo.motd
      - ./certs:/ircd/certs:ro
    deploy:
      placement:
        constraints:
          - "node.role == manager"
      restart_policy:
        condition: on-failure
      replicas: 1

  matterbridge:
    image: 42wim/matterbridge:stable
    container_name: matterbridge
    restart: unless-stopped
    depends_on:
      - atlchat
    volumes:
      - ./matterbridge.toml:/etc/matterbridge/matterbridge.toml:ro

volumes:
  data:
